server:
  port: 8090    #服务端口



####################
# Spring 配置
####################
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源配置
    url: jdbc:mysql://localhost:3306/devicedb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql04141015
    driver-class-name: com.mysql.cj.jdbc.Driver


####################
# JWT 配置
####################
manage:
  jwt:
    secret: fanffafw;asfkaweg # token密钥
    expiration: 60            # token过期时间 秒
    header: JWTHeaderName     # HearName用于接受前端传递的token


####################
# Mybatis-plus 配置
####################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
    map-underscore-to-camel-case: true                    # 开启驼峰命名
  mapper-locations: classpath*:com/dingjn/manage/persistence/mapper/**/*.xml #Mapper映射文件地址，多moudle要用classpath*
